### ISSUE TITLE
[Bug] Wrong "size" value in _delta_log metadata files in "Pulsar to Lakehouse" sink connector (target format Delta Lake)

### ISSUE THREAD

**Issue by msetkin** [streamnative/pulsar-io-lakehouse#170]
**Describe the bug**
We are using a "Pulsar to Lakehouse" sink connector, trying to offload Pulsar topic's content to the S3 storage in Delta format, exactly as it was showed [here](https://streamnative.io/blog/release/2022-08-17-announcing-the-delta-lake-sink-connector-for-apache-pulsar/).
The resulting files structure that we get in S3 after a short iteration:
````
|-- _delta_log
|   |-- 00000000000000000000.json
|    -- 00000000000000000001.json
|-- part-0000-091d0c83-15ca-43bd-9919-355ab559a3c0-c000.snappy.parquet
````

When we try to read this content with Spark:
````
ddl_query = f"CREATE TABLE {database_name}.{table_name}_delta \
                USING DELTA \
                LOCATION 's3://some/bucket'"
spark.sql(ddl_query)
spark.sql(f"select * from {database_name}.{table_name}_delta").show(5)
````

it fails with an exception:
`Caused by: java.lang.RuntimeException: s3a://some/bucket/part-0000-091d0c83-15ca-43bd-9919-355ab559a3c0-c000.snappy.parquet is not a Parquet file. Expected magic number at tail, but found [28, 21, 2, 21]`

When we try to debug it, we find out that the actual `*.parquet` file size is `725 bytes`, while in the `_delta_log/00000000000000000001.json` we see that the `'size'` parameter equals to `16`:
````
{"commitInfo":{"timestamp":1668373624666,"operation":"WRITE","operationParameters":{},"readVersion":0,"isolationLevel":"Serializable","isBlindAppend":true,"operationMetrics":{},"engineInfo":"pulsar-sink-connector-version-2.9.1 Delta-Standalone/0.3.0"}}
{"txn":{"appId":"pulsar-delta-sink-connector","version":1,"lastUpdated":1668373624658}}
{"add":{"path":"part-0000-091d0c83-15ca-43bd-9919-355ab559a3c0-c000.snappy.parquet","partitionValues":{},"size":16,"modificationTime":1668373624659,"dataChange":true,"stats":"{}"}}
````

When we edit manually this file, set `"size"=725` (which is the actual file size), then our Spark code works.
We tried to do this with two versions of the connector: 2.9.1 (which was demonstrated upon the link above by Streamnative at the conference), and with 2.10.1.12 (latest at the moment), both with "cloud" version of *.nar which writes to S3, and with another one that writes the files locally. The result is the same.

**To Reproduce**
1. Run Pulsar (in our case it was a standalone instance in Docker from an image apachepulsar/pulsar:2.10.2)
2. Download a file "pulsar-io-lakehouse-2.10.1.12.nar", copy it inside a container's class path
3. Create a topic in Pulsar
4. Instantiate a connector: `bin/pulsar-admin sinks create --sink-config-file /tmp/jar/config.yaml`
the content of config.yaml:
````
tenant: public
namespace: default
name: my-topic-2
parallelism: 1
inputs:
- my-topic-2
archive: /tmp/jar/pulsar-io-lakehouse-2.10.1.12.nar
processingGuarantees: EFFECTIVELY_ONCE
configs:
 type: delta
 maxCommitInterval: 120
 maxRecordsPerCommit: 10000000
 tablePath: file:///tmp/output/test_sink_v1
 processingGuarantees: "EXACTLY_ONCE"
 deltaFileType: "parquet"
 subscriptionType: "Failover"
````
5. Make sure that the connector works: `bin/pulsar-admin sinks status --name my-topic-2`
6. Produce something to a topic
7. Observe the output files from a connector

**Expected behavior**
We assume that the file size `in _delta_log/*.json`'s must fit to the physical size of the `*.parquet` files as a result of this sink connector (when Delta target format is chosen), so that downstream appliations, such as Spark, could read this result as Delta format without throwing exceptions.

**Environment**
 - OS: inside a docker: apachepulsar/pulsar:2.10.2
 - Pulsar version: 2.10.2
 - Deployment: standalone
 - Connector/offloader/protocol handler/... version: pulsar-io-lakehouse-2.10.1.12.nar
